# Reference
- https://pytorch.org/docs/0.4.0/nn.html
- https://pytorch.org/tutorials/
- https://ratsgo.github.io/machine%20learning/2017/10/12/terms/
- https://github.com/DSKSD/Pytorch_Fast_Campus_2018

In [2]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import numpy as np
from collections import OrderedDict

torch.manual_seed(1)

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# What is a PyTorch?
- Tensor와 Optimizer, Neural Net등 GPU연산에 최적화된 모듈을 이용하여 빠르게 딥러닝 모델을 구현할 수 있는 프레임워크
Facebook이 밀고 있던 lua기반의 torch를 python버전으로 포팅함.

# > Pytorch Basic
- Tensor
- autograd
- nn
- optim

## 1. Tensor

wiki >
 - 텐서란 선형 관계를 나타내는 기학적 대상이다.  
 (https://ko.wikipedia.org/wiki/%ED%85%90%EC%84%9C#%EC%A0%95%EC%9D%98)
 
PyTorch > 
 - Tensor는 N차원 배열이며, PyTorch는 Tensor연산을 위한 다양한 함수들을 제공함.   
 - numpy와 다르게 GPU를 활용해 수치 연산을 가속화 할 수 있음.  
 
### 1.1 Create tensor
- 다양한 방법으로 Tensor타입의 자료형을 만들 수 있음.

#### 1.1.1 파이썬 리스트로부터 생성

In [4]:
V_data= [1., 2., 3.] 
V= torch.Tensor(V_data)
print('<vector> :\n' ,V)


<vector> :
 tensor([ 1.,  2.,  3.])


In [3]:
V_data= [1., 2., 3.] 
V= torch.Tensor(V_data)
print('<vector> :\n' ,V)

M_data= [[1.,2.,3.],[4.,5.,6.]] # 매트릭스
M= torch.Tensor(M_data)
print('<matrix> :\n', M)

T_data= [[[1.,2.],[3.,4.]],[[4.,5.],[6.,7.]]]
T= torch.Tensor(T_data)
print('<3d Tensor> :\n', T)

T_data= T.tolist()
print('<Tensor->list>:\n', T_data)

<vector> :
 tensor([ 1.,  2.,  3.])
<matrix> :
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])
<3d Tensor> :
 tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 4.,  5.],
         [ 6.,  7.]]])
<Tensor->list>:
 [[[1.0, 2.0], [3.0, 4.0]], [[4.0, 5.0], [6.0, 7.0]]]


#### 1.1.2  numpy ndarray객체로부터 Tensor생성

In [9]:
V_data= np.array([1, 2, 3]) 
V= torch.Tensor(V_data)
print('<vector> :\n' ,V)

M_data= np.array([[1.,2.,3.],[4.,5.,6.]]) # 매트릭스
M= torch.Tensor(M_data)
print('<matrix> :\n', M)

T_data= np.array([[[1.,2.],[3.,4.]],[[4.,5.],[6.,7.]]])
T= torch.Tensor(T_data)
print('<3d Tensor> :\n', T)

T_data= T.numpy()
print('<Tensor->numpy ndarray>:\n', T_data)

<vector> :
 tensor([ 1.,  2.,  3.])
<matrix> :
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])
<3d Tensor> :
 tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 4.,  5.],
         [ 6.,  7.]]])
<Tensor->numpy ndarray>:
 [[[1. 2.]
  [3. 4.]]

 [[4. 5.]
  [6. 7.]]]


#### 1.1.3 기타 다른 생성 방법들

In [7]:
x= torch.zeros(2,3)
print('<zeros tensor> :\n', x)

x= torch.ones(2,3)
print('<ones tensor> :\n', x)

x= torch.randn(3,4) 
print('<sample Normal distribution> :\n', x)

x= torch.randperm(5)
print('<permutation of integers from 0 to n-1(LongTenosr)> :\n', x)

<zeros tensor> :
 tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
<ones tensor> :
 tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])
<sample Normal distribution> :
 tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
        [-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])
<permutation of integers from 0 to n-1(LongTenosr)> :
 tensor([ 3,  1,  0,  2,  4])


### 1.2. Indexing, Slicing, Joining, Mutating Ops
- PyTorch의 Tensor 자료형도 numpy의 ndarray와 같이 indexing, slicing, joining이 가능함.  

#### 1.2.1. indexing

In [12]:
x= torch.randn(3,4,5)
print(x.size())
print(x[0,:,:].size())

torch.Size([3, 4, 5])
torch.Size([4, 5])


#### 1.2.2 select_index
- LongTensor로 Tensor에 행 또는 열에 해당하는 값을 가져올 수 있음.

In [16]:
x= torch.randn(3,4)
print('x.shape :',x.shape)
print('x :',x)
indices= torch.LongTensor([0,2])
print('indices:', indices)
print('')
print('select 0 dim: ', torch.index_select(x, 0, indices))
print('select 1 dim: ', torch.index_select(x, 1, indices))

x.shape : torch.Size([3, 4])
x : tensor([[-1.6428,  0.9803, -0.0421, -0.8206],
        [ 0.3133, -1.1352,  0.3773, -0.2824],
        [-2.5667, -1.4303,  0.5009,  0.5438]])
indices: tensor([ 0,  2])

select 0 dim:  tensor([[-1.6428,  0.9803, -0.0421, -0.8206],
        [-2.5667, -1.4303,  0.5009,  0.5438]])
select 1 dim:  tensor([[-1.6428, -0.0421],
        [ 0.3133,  0.3773],
        [-2.5667,  0.5009]])


#### 1.2.3 torch.masked_select
- torch.Tenosr타입의 ge메소드는 인자값보다 큰 경우를 1 작은 경우를 0인 동일한 크기의 Tensor를 생성함.
- masked_select는 마스킹된 값을 Tensor로 반환함.

In [23]:
x= torch.randn(3,4)
print('tensor :',x)

mask= x.ge(0.5)
print('ge method', mask)

print(torch.masked_select(x,mask))

tensor : tensor([[-0.4057,  1.1341, -1.1115,  0.3501],
        [-0.7703, -0.1473,  0.6272,  1.0935],
        [ 0.0939,  1.2381, -1.3459,  0.5119]])
ge method tensor([[ 0,  1,  0,  0],
        [ 0,  0,  1,  1],
        [ 0,  1,  0,  1]], dtype=torch.uint8)
tensor([ 1.1341,  0.6272,  1.0935,  1.2381,  0.5119])


#### 1.2.4 torch.cat
- Tensor들을 concatenate함

In [24]:
x_1= torch.rand(2,5)
y_1= torch.rand(3,5)
z_1= torch.cat([x_1, y_1],0)
print(z_1.size())

torch.Size([5, 5])


#### 1.2.5 torch.view
- Tensor를 reshape함.

In [25]:
x= torch.randn(2,3,4)
print(x.size())
print(x.view(2,-1).size())

torch.Size([2, 3, 4])
torch.Size([2, 12])


In [27]:
x.view(2,4,3).size()

torch.Size([2, 4, 3])

#### 1.2.6 torch.squeeze
- Tensor에서 차원을 제거함. [[1]]->[1]

In [35]:
x= torch.ones(3,1,3)
print(x.size())
print(x.squeeze(1).size())

torch.Size([3, 1, 3])
torch.Size([3, 3])


#### 1.2.7 torch.unsqueeze
- Tensor에서 차원을 추가함. [1]->[[1]]

In [36]:
print(x.size())
print(x.unsqueeze(1).size())

torch.Size([3, 1, 3])
torch.Size([3, 1, 1, 3])


### 1.3 Math Operation
- Tensor타입을 연산할 수 있음.

#### 1.3.1 add
- 텐서의 각 scalar값을 각 element별로 더해줌

In [37]:
x= torch.Tensor([1,2,3])
y= torch.Tensor([3,4,5])
z=x+y
print(z)
print(torch.add(x,y))

tensor([ 4.,  6.,  8.])
tensor([ 4.,  6.,  8.])


#### 1.3.2 sum
- Tensor의 모든 scalar값을 더해준다.

In [38]:
x= torch.Tensor([1.,2.,3.])
print(x.sum())
print(sum(x))

tensor(6.)
tensor(6.)


#### 1.3.3 dot product 
- Tensor들끼리 dot product를 한다.

In [40]:
x= torch.Tensor([1.,2.,3.])
y= torch.Tensor([1.,2.,3.])
z= x.dot(y)
print(z)
print(torch.dot(x,y))

tensor(14.)
tensor(14.)


#### 1.3.4 mul
- Tensor들의 각 scalara값들을 element마다 곱해줌.

In [41]:
x= torch.Tensor([1,2,3])
y= torch.Tensor([3,4,5])
z= x.mul(y)
print(z)

tensor([  3.,   8.,  15.])


#### 1.3.5 mm : matrix multiplication
- matrix multiplication

In [42]:
x= torch.randn(2,3)
y= torch.randn(3,2)
z= x.mm(y)
print(z)
print(z.size())

tensor([[ 2.2664,  0.4295],
        [ 0.2962,  2.1845]])
torch.Size([2, 2])


#### 1.3.6 max 
- scalar 값 중에서 max값을 구해준다.

In [43]:
x= torch.Tensor([[1,2], [3,4], [5,1]])
print(x.max()) # 전체 기준 max
print(x.max(0)) # 차원을 기준해서 max와 그에 해당하는 index
print(x.max(1))

tensor(5.)
(tensor([ 5.,  4.]), tensor([ 2,  1]))
(tensor([ 2.,  4.,  5.]), tensor([ 1,  1,  0]))
